### ISSUE TITLE
v3的service worker会inactive，此时auto-reload和auto-refresh都会失效

### ISSUE THREAD

**Issue by tyn1998** [tomzhu1024/webpack-boilerplate-chrome#1]
tomzhu1024，你好！

最近在折腾v3下的webpack开发体验。非常有缘，你参考的两个仓库正是我在网上高强度冲浪后选出的两个仓库，握个爪~

目前我遇到的问题是，v3下的service worker生命期有限，无论是SSE还是websocket都会在service worker失效后自动断开，显然这会让auto-reload和auto-fresh都失效，因为它们依赖长连接、依赖devServer主动发来的消息。
<img width="446" alt="image" src="https://user-images.githubusercontent.com/32434520/152649005-7ae49c15-8c75-466e-8ade-c0a87170d6f5.png">

我抱着试试的心态在GitHub搜到了你的仓库，描述完美符合我的要求，简直是救星！但是我跑了一下，等到service worker失效后，auto-reload和auto-fresh按照预期（我先看了代码）失效了。你的gif里是打开着background这个控制台界面，这能让它多活一点，但是按照官方的说法最多活5分钟。

不知道你有没有测试过service worker失效后的情况？

期待你的回复，希望能和你多多交流~这个话题实在太难找知己了

参考：
- https://groups.google.com/a/chromium.org/g/chromium-extensions/c/L3EbiNMjIGI

**Comment by tyn1998** [comment]
题外话：gif效果太好了，请问是怎么制作的

**Comment by tyn1998** [comment]
> 你的gif里是打开着background这个控制台界面，这能让它多活一点，但是按照官方的说法最多活5分钟。

驳回：只要devtool界面一直打开着（最小化也无所谓），service worker就不会inactive（起码超过了5分钟）。这个方法在开发环境下是完全能接受的。

所以在Readme中补上一句“请保持service worker的devtool界面开启”也许是目前最优雅的方式了。

**Comment by tomzhu1024** [comment]
你好！很荣幸我的工具能给你的工作带来些许方便！

service worker 的失活问题我目前也没有很好的解决方案，和你说的方法一样，我一般也是依靠手动打开 devtool 来使它保持活跃的。感谢你的提醒，我会把这个信息加入到 ReadMe 中的。

关于 GIF 制作：我的 GIF 是使用一个叫 [ScreenToGif](https://www.screentogif.com/) 的软件制作的（只支持 Windows）。

**Comment by tyn1998** [comment]
谢谢回复~service worker inactive对那些生产环境依赖长连接的插件挺麻烦的。意识到开发环境多开一个devtool页面完全没毛病后，真是豁然开朗啊。这几天可折磨人了。

>关于 GIF 制作：我的 GIF 是使用一个叫 [ScreenToGif](https://www.screentogif.com/) 的软件制作的（只支持 Windows）。

Mac用户享受不到了（不过Mac下的Gifox也挺不错的，试了好多款这个最棒）

**Comment by tomzhu1024** [comment]
确实，Manifest 升级到 V3 之后有很多非常大的改动，对老的开发脚手架差不多就是毁灭性的打击……我也是因为有这个需求，特意写了一个可以在 Manifest V3 下工作的脚手架。

>Mac用户享受不到了（不过Mac下的Gifox也挺不错的，试了好多款这个最棒）

对的，Mac 用户就不能用这个软件了。其实我最近也换到了 Mac 平台，感谢推荐！
