### ISSUE TITLE
一处小困惑

### ISSUE THREAD

**Issue by tyn1998** [tomzhu1024/webpack-boilerplate-chrome#2]
<img width="989" alt="image" src="https://user-images.githubusercontent.com/32434520/152669795-c6157029-e9d2-4326-a0b8-22748553651f.png">

content script的auto-refresh其实分了两步：
1. reload extension  <--  chrome.runtime.reload()
2. reload tabs that use content script  <--  window.location.reload()

如上图，我的问题是reload extension这一步不应该尽快完成吗，为什么要延后1秒？在contentScriptClient.js中，tab的刷新延迟1秒正是为了等chrome.runtime.reload()把最新的content script加载进来。这是不是冲突了。

**Comment by tomzhu1024** [comment]
我检查了一下，你说的是对的。感谢提醒！虽然目前功能是正常的，但是此处确实可以更加合理一些。

**Comment by tyn1998** [comment]
嗯~
